-- Keyboards / keypads feature. Run once in the Supabase SQL editor.

-- 1) Device catalog.
create table if not exists keyboards (
  id text primary key,               -- slug, e.g. 'wooting-60he'
  name text not null,
  brand text,
  type text not null default 'keyboard',  -- 'keyboard' | 'keypad'
  layout jsonb,                      -- keypads: { "rows": [ [ {"label":"Z"}, {"label":"X"} ] ] }
                                     -- keyboards: null -> the profile shows just the tap keys
  model_url text,                    -- optional image / 3D render of the device
  created_at timestamptz not null default now()
);

-- 1b) USB ids for WebHID auto-detect (Wooting vendor + VIA/QMK raw-HID boards).
alter table keyboards add column if not exists vendor_id integer;      -- e.g. 12771 (0x31e3 Wooting)
alter table keyboards add column if not exists product_id integer;

-- 2) User columns: chosen device + the keys they tap.
alter table users add column if not exists keyboard text;              -- keyboards.id
alter table users add column if not exists keyboard_keys jsonb;        -- ["Z","X"]

-- 2b) Requests for devices not yet in the catalog.
create table if not exists keyboard_requests (
  id bigint generated by default as identity primary key,
  user_id text,
  name text not null,
  brand text,
  vendor_id integer,
  product_id integer,
  note text,
  status text not null default 'open',   -- 'open' | 'done'
  created_at timestamptz not null default now()
);

-- 3) Curated seed of known osu! devices (edit/extend in /admin later).
insert into keyboards (id, name, brand, type, layout) values
  ('kbd-2key', '2-Key Keypad', 'Generic', 'keypad',
     '{"rows":[[{"label":"Z"},{"label":"X"}]]}'),
  ('kbd-3key', '3-Key Keypad', 'Generic', 'keypad',
     '{"rows":[[{"label":"Z"},{"label":"X"},{"label":"C"}]]}'),
  ('kbd-4key', '4-Key Keypad', 'Generic', 'keypad',
     '{"rows":[[{"label":"Z"},{"label":"X"},{"label":"C"},{"label":"V"}]]}'),
  ('dotio', 'Dot io Keypad', 'Dot io', 'keypad',
     '{"rows":[[{"label":"Z"},{"label":"X"}]]}'),
  ('wooting-two-he', 'Wooting Two HE', 'Wooting', 'keyboard', null),
  ('wooting-60he', 'Wooting 60HE', 'Wooting', 'keyboard', null),
  ('wooting-80he', 'Wooting 80HE', 'Wooting', 'keyboard', null),
  ('ducky-one-2-mini', 'Ducky One 2 Mini', 'Ducky', 'keyboard', null),
  ('ducky-one-3-mini', 'Ducky One 3 Mini', 'Ducky', 'keyboard', null),
  ('razer-huntsman-mini', 'Razer Huntsman Mini', 'Razer', 'keyboard', null),
  ('steelseries-apex-pro', 'SteelSeries Apex Pro', 'SteelSeries', 'keyboard', null),
  ('gmmk-pro', 'GMMK Pro', 'Glorious', 'keyboard', null)
on conflict (id) do nothing;
